<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Validator.cs" Link="Validator.cs" />
    <Compile Include="../Derivation.cs" Link="Derivation.cs" />
    <Compile Include="../ParseTree.cs" Link="ParseTree.cs" />
  </ItemGroup>

</Project>